### ISSUE TITLE
Home Assistant compatibility

### ISSUE THREAD

**Issue by q20** [MycroftAI/mimic3#3]
Hey there

Attempting to add Mimic 3 (docker container) as a drop-in replacement for MaryTTS is not working:

I have added the following to the configuration.yaml:

```
tts:
  - platform: marytts
    host: "localhost"
    port: 59125
    language: "en_UK"
    voice: apope_low
```

When checking the configuration's validity, the following error is thrown:

![image](https://user-images.githubusercontent.com/17024596/176658888-da67d0cb-3f07-4abb-ae10-73bbd2ddab71.png)

If I swap en_UK to en_GB, this check passes:

![image](https://user-images.githubusercontent.com/17024596/176659043-f8fbead3-e581-4e83-82df-c02b01f5cf7b.png)

So, is this a Home Assistant or Mimic 3 issue? Can I manually rename the en_UK voice to en_GB?

**Comment by krisgesling** [comment]
Hey thanks for the heads up on this. 

Will have to take a look and see what the best approach is here.

**Comment by krisgesling** [comment]
Hey @q20 - can you try removing the `language` parameter and including the full [voice key](https://mycroft-ai.gitbook.io/docs/mycroft-technologies/mimic-tts/mimic-3#voice-keys) for `voice`?

That would make your config:
```
tts:
  - platform: marytts
    host: "localhost"
    port: 59125
    voice: en_UK/apope_low
```
